CREATE TABLE SCORES (	
	USERID INT NOT NULL,
	GAMENAME VARCHAR(50) NOT NULL,
	STARTTIME VARCHAR(25) NOT NULL,
	ENDTIME VARCHAR(25) NOT NULL,
	SCORE INT NOT NULL
);

CREATE TABLE USERS (
	ID INT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
);